### ISSUE TITLE
Board re-design

### ISSUE THREAD

**Issue by alphaville** [QUB-ASL/bzzz#57]
I've created this issue to keep track of the re-design of the board. Feel free to comment. Some notes:

- We'll keep the boards separately and they'll be connected by a USB cable
- We need to figure out how to power both boards neatly (Will the ESP be powered via the USB cable?)
- The OS on RPi will be on a USB stick
- Put four holes on the board; we can use screws and spacers to keep the RPi and our board (with the ESP32) together

We should also keep the grb files (and a PNG version) on GitHub. Share your throughs below.

## TODOs

- [x] Initial electric schematic (prepare and contribute to GitHub)
- [x] Review of initial schematic
- [x] Create Gerber file for PCB
- [x] Compile list of components to purchase

Until then, let us modify the existing board

**Comment by alphaville** [comment]
@jamie-54 @gunturiCM Meanwhile, as we discussed yesterday, let us use the current version of the board and cut the UART connection between the RPi and the ESP.

**Comment by alphaville** [comment]
@jamie-54 @gunturiCM I cut the serial connection between the RPi and the ESP (see on the left). The board should work now if we use a USB cable and a USB stick.

![image](https://github.com/QUB-ASL/bzzz/assets/125415/fb735df5-d764-4644-922e-57cddccaf699)

**Comment by alphaville** [comment]
Also, if we use the cable it would be good to rotate the ESP32 so that the two USB ports are one the same side

![image](https://github.com/QUB-ASL/bzzz/assets/125415/4780d654-6e27-44ac-b704-925be090fc6f)

**Comment by alphaville** [comment]
> Professor, I think it is a better idea to make a proper schematic first rather than designing the PCB directly. When we have everything needed on the board, we will start designing the PCB. It is standard practice to make the schematic first. The ESP can be powered by the native USB port.

Chandra, could you take the lead and make a first draft of the schematic?
